---
- name: Demonstrate error handling in ansible using block...resucue.. always
  hosts: localhost
  become: true
  tasks:
   - block:
     - name: Task to install a package
       yum:
        name: mariadb1
        state: installed
     rescue:
       - name: Print rescue message
         debug:
          msg: I am in rescue
     always:
       - name: print always block message
         debug:
          msg: I am in always

... #End of the play
